services:
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.7.2-cu128
    ports:
      - "2221:8880"
    gpus: all
    environment:
      DEFAULT_RESPONSE_FORMAT: wav
      KOKORO_PRELOAD_LANGS: a
    restart: unless-stopped
